### ISSUE TITLE
USB storage doesnt work

### ISSUE THREAD

**Issue by JonathanJhon55** [serxo/ar150-wifi_pineapple#1]
Hey mate!

Thanks for this, I am looking for this my whole life..

Actually the USB storage doesn't work, I formatted my USB drive to 2 partitions both ext4.
Followed the steps, but didn't do anything.

Any tips for this? Many thanks!

**Comment by serxo** [comment]
I tested it with some cheap usb drives and all worked ok. Sometimes all you need is to reboot and check if the fstab is saved with the correct mount point, also you can check on the dmesg log if there´s something on dev/sda1 and dev/sda2.

Mine has this entry:  **sda: sda1 sda2**

 Remember that to create the swap you need to ssh in and enter the command "mkswap /dev/sda2". 
Basically I followed the steps of this official tutorial [https://forums.hak5.org/index.php?/topic/25882-how-to-enable-usb-mass-storage-with-swap-partition/](url)

My fstab for storage and swap looks like this:

config 'global'
	option	anon_swap	'0'
	option	anon_mount	'0'
	option	auto_swap	'1'
	option	auto_mount	'1'
	option	delay_root	'5'
	option	check_fs	'0'



config 'mount'
	option	target		'/sd'
	option	device		'/dev/sda1'
	option	fstype		'ext4'
	option	options		'rw,sync'
	option	enabled		'1'
        option	enabled_fsck		'0'

config 'swap'
        option      device             '/dev/sda2'
        option      enabled           '1'

I included the minimum kernel modules needed for USB usage, maybe your device is not fully compatible. When I have time I will try to compile again including more drivers, hopefully there are no conflicts with the firmware.

**Comment by serxo** [comment]
I successfully​ tested the USB storage with more devices like Kingston datatraveler 101 8gb, micro SD adapters and a Sandisk cruzer fit 16GB so I think this issue can be closed.
