### ISSUE TITLE
Problems with USB hub and wifi Dongles.

### ISSUE THREAD

**Issue by serxo** [serxo/ar150-wifi_pineapple#2]
The client mode on a second wireless interface (TP-LINK WN722) when connected throw a USB hub doesn't associate correctly with the access point.
The LEDs of the dongle blink correctly ( sign that this is not a voltage issue ) .Dmesg shows that the device is properly detected and the drivers are loaded without errors, the network scanner works perfect also
 The error comes from the network manager, it specifies that there's no PHY4 for device 'radio1' , when the same device is connected directly on the USB port this error doesn't occur, so this is possibly a wireless config issue ( the USB storage in the hub works well, so the incompatibility is not global ) . I will try to find by myself what's going wrong but any help is much appreciated :)

**Comment by serxo** [comment]
Fixed up!! I made a factory reset and the errors disappeared. Probably playing with file permissions was part of the problem...
Now it´s a fully compatible setup of hardware for the Wifi Pineapple software. PineAP, modules and storage are working like a charm.
I will post a demo using Evil portal and other interesting modules, plus a comparison between the original hardware and this version.

**Comment by meunlo** [comment]
> I will post a demo using Evil portal and other interesting modules, plus a comparison between the original hardware and this version.

very much look forward to that.
