### ISSUE TITLE
Cannot use any usb device

### ISSUE THREAD

**Issue by FSEC-DALMASIAN** [serxo/ar150-wifi_pineapple#8]
im using a usb hub to connect a wifi adapter which gets picked up and i also have a lexar 8gb usb which is also getting picked up under the usb tab but cannot install any modules on it.

**Comment by nivong** [comment]
is it mounted?

**Comment by careyer** [comment]
You have to alter the fstab content in order to make it mount correctly as "sdcard"

**Comment by nivong** [comment]
@careyer  It needs to be /sd not /sdcard
```
config global
	option anon_swap '0'
	option anon_mount '0'
	option auto_swap '1'
	option auto_mount '1'
	option delay_root '5'
	option check_fs '0'

config mount
	option target '/sd'
	option device '/dev/sda1'
	option fstype 'auto'
	option options 'rw,sync'
	option enabled	'1'
        option enabled_fsck '0'

config 'swap'
        option device '/dev/sda2'
        option enabled '1'
```

**Comment by meunlo** [comment]
Any good write ups / guides for noobs on this? I was able to mount my 2gb
SD card before the update and i'm hitting a brick wall remembering exactly
what I did to mount it the first time... Any pointers appreciated!

**Comment by nivong** [comment]
```mount /sd /dev/sda1```
Is all you need after you entered SSH connection

**Comment by FSEC-DALMASIAN** [comment]
wow i  actually just saw the mistake careyer made, listened to him and nothing. now it actually works with a usb. 

Thanks
